name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Build and Push
        run: |
          docker build -t young5097/edrink24-server:latest .
          docker push young5097/edrink24-server:latest

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ec2-user@15.152.201.149 << 'EOF'
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          sudo docker pull young5097/edrink24-server:latest
          
          # Stop and remove all containers
          sudo docker stop $(sudo docker ps -a -q) || true
          sudo docker rm $(sudo docker ps -a -q) || true
          
          # Run the new container
          sudo docker run -d -p 8090:8090 young5097/edrink24-server:latest
          EOF


